### ISSUE TITLE
[feature request] Add radix based parsing

### ISSUE THREAD

**Issue by dmtrKovalenko** [rodrimati1992/konst#13]
The `from_str_radix` from core is not even an unstable const fn so it will be very useful to have it available in konst. 

BTW thanks your library saved me a lot of work :)

**Comment by SCingolani** [comment]
+1 on this request and on the thanks for the library!

**Comment by rodrimati1992** [comment]
Closing this issue since `std` constified [`from_str_radix`](<https://doc.rust-lang.org/std/primitive.u8.html#method.from_str_radix>) some time ago and const-stabilized it in the latest stable.
