### ISSUE TITLE
konst::ptr::nonnull::new (and maybe also konst::ptr::is_null) is unsound due to out-of-bounds pointers.

### ISSUE THREAD

**Issue by theemathas** [rodrimati1992/konst#32]
Using stable rust 1.83.0, and the `konst` crate version `0.3.15`, I can use [`konst::ptr::nonnull::new`](https://docs.rs/konst/0.3.15/konst/ptr/nonnull/fn.new.html) to cause undefined behavior in safe code as follows.

```rust
static VAL: i32 = 1i32;

pub const X: Option<std::ptr::NonNull<i32>> = {
    let p = (&raw const VAL).wrapping_byte_add(size_of::<i32>() + 1);
    konst::ptr::nonnull::new(p.cast_mut())
};
```

The code above needs to check if an out-of-bounds pointer is null. This check is impossible at compile time, because the static might (e.g., due to ASLR) be placed an address that ends up making the out-of-bounds pointer null. Compiling this code produces the following error:

```
error[E0080]: it is undefined behavior to use this value
 --> src/lib.rs:3:1
  |
3 | pub const X: Option<std::ptr::NonNull<i32>> = {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<enum-tag>: encountered pointer to alloc1+0x5, but expected a valid enum tag
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
  = note: the raw bytes of the constant (size: 8, align: 8) {
              ╾─────alloc1+0x5──────╼                         │ ╾──────╼
          }

For more information about this error, try `rustc --explain E0080`.
```

The error notes that undefined behavior has been detected. And as per [RFC 3016](https://rust-lang.github.io/rfcs/3016-const-ub.html), undefined behavior during const evaluation is not guaranteed to be caught, and if uncaught, may result in undefined behavior at runtime.

I am unable to demonstrate undefined behavior with [`konst::ptr::is_null`](https://docs.rs/konst/0.3.15/konst/ptr/fn.is_null.html), but it is possible that it also has issues.

Of note, the [`is_null`](https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null-1) and [`NonNull::new`](https://doc.rust-lang.org/nightly/std/ptr/struct.NonNull.html#method.new) methods in std (which are scheduled to be const-stable in 1.84.0 and 1.85.0, respectively) may panic for out-of-bounds pointers. (Note that the stable docs for these two methods are currently incorrect, so I'm linking to the nightly docs.)

**Comment by rodrimati1992** [comment]
Thanks for pointing this unsoundness out, I'll deprecate these functions in a 0.3 patch release soon, and then remove them in 0.4.0 .
